components {
  id: "enemy script"
  component: "/main/enemies/shooter/enemy shooter.script"
}
components {
  id: "shooter"
  component: "/main/enemies/shooter/shooter.factory"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"shooter guy\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/sprites.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "death"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"e-head\"\n"
  "mask: \"feet\"\n"
  "mask: \"water\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 12.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"head\"\n"
  "  }\n"
  "  data: 16.11442\n"
  "  data: 5.377141\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "general collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"ground\"\n"
  "mask: \"L-Wall\"\n"
  "mask: \"R-Wall\"\n"
  "mask: \"Roof\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -4.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"enemy\"\n"
  "  }\n"
  "  data: 13.685274\n"
  "  data: 10.998942\n"
  "  data: 5.0\n"
  "}\n"
  ""
}
