components {
  id: "player move"
  component: "/main/player/scripts/Player move.script"
}
components {
  id: "water opacity"
  component: "/main/player/scripts/water opacity.script"
}
components {
  id: "gui"
  component: "/main/player/HUD/gui.gui"
}
embedded_components {
  id: "collision- general"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.0\n"
  "restitution: 0.0\n"
  "group: \"player\"\n"
  "mask: \"water\"\n"
  "mask: \"L-Wall\"\n"
  "mask: \"R-Wall\"\n"
  "mask: \"Roof\"\n"
  "mask: \"enemy\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -0.75\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"body\"\n"
  "  }\n"
  "  data: 7.503147\n"
  "  data: 11.594651\n"
  "  data: 0.05\n"
  "}\n"
  "locked_rotation: true\n"
  ""
}
embedded_components {
  id: "collision-floor"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"feet\"\n"
  "mask: \"ground\"\n"
  "mask: \"e-head\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -12.75\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"feet\"\n"
  "  }\n"
  "  data: 6.7698426\n"
  "  data: 0.073592\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Placeholder guy\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 32.0\n"
  "  y: 32.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/sprites.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.8
    y: 0.8
  }
}
