function init(self)
	--literally just sets camera as active.
	msg.post("#camera", "acquire_camera_focus")
	msg.post("@render:", "use_camera_projection")
end
function update(self, dt)
	--camera follows player.
	local pos = go.get_position()
	local new_pos = go.get_position("main:/Player")
	--camera smoothing.
	local x_y_vector = vmath.vector3(new_pos.x, new_pos.y, pos.z)
	pos = vmath.lerp(0.08, pos, x_y_vector)
	go.set_position(pos)
end